iis-website-add-release-number-to-response-header: Fix error
Fixed the following exception:
```
Exception calling "GetSection" with "2" argument(s): "Filename: redirection.config
Error: Cannot read configuration file
```
Credit for revealing the root cause (in some instances the script would load the incorrect assembly, which in turn would try to modify the incorrect configuration file):
https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/191#issuecomment-238687014
Credit for the solution:
https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/462